[project]
name = "call-analyser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "elevenlabs>=2.3.0",
    "ffmpeg-python>=0.2.0",
    "flask>=3.1.1",
    "openai>=1.86.0",
    "tiktoken>=0.9.0",
]
